### ISSUE TITLE
Code Updates Coming?

### ISSUE THREAD

**Issue by havester** [codefoster/javascript-minecraft-mods#1]
I enjoyed your presentation at Boise Code Camp 2017.  If my notes are correct from your minecraft/scriptcraft presentation, your code had a few more comments (things to try next) and updates than what I see here.  Is the code here the same version as what your presentation used or are there updates coming?

Thanks for putting this together!

**Comment by codefoster** [comment]
Sorry this is so late, @harvester. I did just look and had some code I'd neglected to push. I have now. Have fun.
